"""empty message

Revision ID: 135787632ba4
Revises: fa0d468d5e3d
Create Date: 2023-04-30 23:23:09.475355

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '135787632ba4'
down_revision = 'fa0d468d5e3d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('visualizations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=60), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('type', sa.String(length=60), nullable=False),
    sa.Column('parameters', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], name=op.f('fk_visualizations_post_id_posts')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_visualizations_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_visualizations'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('visualizations')
    # ### end Alembic commands ###
