"""empty message

Revision ID: 3a72b3e8c3ff
Revises: 263ce79cc956
Create Date: 2023-05-01 02:29:16.738828

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a72b3e8c3ff'
down_revision = '263ce79cc956'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visualizations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dimension', sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visualizations', schema=None) as batch_op:
        batch_op.drop_column('dimension')

    # ### end Alembic commands ###
