"""empty message

Revision ID: 786b5065a922
Revises: 
Create Date: 2023-04-30 21:48:08.134663

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '786b5065a922'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_model',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=125), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_model')),
    sa.UniqueConstraint('email', name=op.f('uq_user_model_email')),
    sa.UniqueConstraint('username', name=op.f('uq_user_model_username'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_model')
    # ### end Alembic commands ###
